version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    container_name: k8scale-zookeeper-1
    ports:
      - "2181:2181"
  kafka:
    image: k8scale-kafka:0.1 
    container_name: k8scale-kafka-1
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
